### Ver usuarios registrados
GET http://localhost:3000/users

### Registrar usuario
POST http://localhost:3000/register
Content-Type: application/json

{
    "nombre": "Cesar",
    "apellido": "Villalobos",
    "username": "villalobos1803",
    "correo": "cavc@gmail.com",
    "password": "boliviano"
}

### Iniciar sesion
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Idiarj",
    "password": "16012004"
}

### Ver perfiles del usuario logeado
GET http://localhost:3000/profiles

### Ver usuarios logeados
GET http://localhost:3000/login

### Cerrar sesion
POST http://localhost:3000/logout

### Ver usuario
GET http://localhost:3000/users/Idiarj

### Cambiar contrasena
PATCH http://localhost:3000/changePassword
Content-Type: application/json

## Recuperar Contrasena
POST http://localhost:3000/forgot-password
Content-Type: application/json

{
    "correo": "andresburgosj@gmail.com"
}

{
    "newPass": "16012004id"
}


### Ver proyectos el usuario logeado
GET http://localhost:3000/projects 
