### Ver usuarios registrados
GET http://localhost:3000/users

### Registrar usuario
POST http://localhost:3000/register
Content-Type: application/json

{
    "nombre": "Idiar",
    "apellido": "Chacin",
    "username": "IdiArj",
    "cedula": 30217559,
    "correo": "idiar16@gmail.com",
    "password": "16012004"
}

### Iniciar sesion
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Idiarj",
    "password": "16012004"
}



### Ver proyectos el usuario logeado
GET http://localhost:3000/projects 

### Home
GET http://localhost:3000/home

### Crear un proyecto
POST http://localhost:3000/projects/crearProyecto
Content-Type: application/json


{
    "projectName": "Sistema de Gestion Central de Proyectos",
    "objective": "Proyecto de la materia Web 2",
    "members": [
        {
            "cedula": 30106795,
            "profiles": ["Desarrollador"]
        },
        {
            "cedula": 30819565,
            "profiles": ["Desarrollador"]   
        }
    ],
    "startDate": "2024-05-07",
    "endDate": "2024-07-28",
    "state": "Creado"
}